name: semo
description: "A streaming application"
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  cloud_firestore: ^5.4.3
  firebase_remote_config: ^5.1.3
  flutter_inappwebview: ^6.1.4
  flutter_settings_ui: ^3.0.1
  flutter_vlc_player: ^7.4.2
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  package_info_plus: ^8.0.2
  page_transition: ^2.1.0
  path_provider: ^2.1.4
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
